#
# Copyright (c) 2018 Itron, Inc.
# All rights reserved.
#
#
TOPDIR = ../../..
CFLAGS += -I$(TOPDIR)/mmesh/x509cache \
          -I$(TOPDIR)/elliptic/src/headers


TARGET = x509cache

C_SRCS =	x509cache.c


include ../libs.mk
include $(BUILD_ROOT)/mk/rules.mk
